# Generated by Django 2.2.16 on 2023-11-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('lat', models.FloatField(verbose_name='lat')),
                ('lng', models.FloatField(verbose_name='lng')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('registration_number', models.CharField(max_length=255, verbose_name='registration_number')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.CharField(choices=[('SEEDING', 'seeding'), ('PROTECTION', 'protection'), ('HARVESTING', 'harvesting'), ('SOIL_PREPARATION', 'soil_preparation')], max_length=255, verbose_name='type')),
                ('speed', models.FloatField(verbose_name='speed')),
                ('depth', models.FloatField(verbose_name='depth')),
                ('flowrate', models.FloatField(verbose_name='flowrate')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(verbose_name='AddDate')),
                ('commit_date', models.DateTimeField(verbose_name='CommitDate')),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('MACHINE_INSPECTION', 'machine_inspection'), ('IN_PROGRESS', 'in_progres'), ('CLOSED', 'closed'), ('PAUSED', 'paused'), ('DONE', 'done')], default='OPEN', max_length=255, verbose_name='status')),
                ('payment', models.FloatField(null=True, verbose_name='payment')),
                ('comment', models.TextField(null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('serial_number', models.CharField(max_length=255, verbose_name='serial_number')),
            ],
        ),
    ]
