# Generated by Django 2.2.16 on 2023-11-17 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL, verbose_name='executor'),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasktracker.Location', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='task',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasktracker.Machine', verbose_name='machine'),
        ),
        migrations.AddField(
            model_name='task',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasktracker.Operation', verbose_name='operation'),
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasktracker.Unit', verbose_name='unit'),
        ),
    ]
