# Generated by Django 2.2.16 on 2023-11-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0003_auto_20231118_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='name',
        ),
    ]
