# Generated by Django 2.2.16 on 2023-11-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0008_auto_20231118_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='plant_name')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasktracker.Plant', verbose_name='plant'),
        ),
    ]
