# Generated by Django 2.2.16 on 2023-11-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0009_auto_20231118_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='flowrate',
        ),
        migrations.AddField(
            model_name='operation',
            name='flow_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='flowrate'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='speed'),
        ),
    ]
