# Generated by Django 2.2.16 on 2023-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0010_auto_20231119_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('MACHINE_INSPECTION', 'machine_inspection'), ('IN_PROGRESS', 'in_progres'), ('ON_MY_WAY', 'on_my_way'), ('CLOSED', 'closed'), ('PAUSED', 'paused'), ('DONE', 'done')], default='OPEN', max_length=255, verbose_name='status'),
        ),
    ]
